version: "3"
containers:
- name: container
  image: ubuntu
  shell: /bin/bash
  memory: 256
  resources:
    memory: 256
- name: testingggg
  image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
  ports:
  - 9200
  environment:
    discovery.type: single-node
  memory: 2048
  resources:
    memory: 2048
virtualmachines:
- name: test-kubernetes
  image: instruqt/k3s-v1-29-10
  shell: /bin/bash
  machine_type: n1-standard-1
  memory: 4096
  cpus: 1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: adcfasd
  image: instruqt/k3s-v1-29-0
  machine_type: n1-standard-1
  memory: 4096
  cpus: 1
  allow_external_ingress:
  - http
  - high-ports
  - https
